### ISSUE TITLE
Go To Fine Calibration Position Button 

### ISSUE THREAD

**Issue by jeffmaeder** [Chris-Annin/AR2#11]
The button on the new version 1.4 is not executing a move to position like in the 1.1 software.

**Comment by Chris-Annin** [comment]
can you tell me more? which button?

**Comment by Chris-Annin** [comment]
I think I see the issue.  im on it.  I'll let you know when I have a fix.

**Comment by Chris-Annin** [comment]
posted updated files.  I believe the bug is fixes as I havnt been able to recreate after.  please confirm

**Comment by Chris-Annin** [comment]
Ok I’ll look again I must be missing something obvious. Thank you for your help and pointing this out.
