### ISSUE TITLE
Excel typo?

### ISSUE THREAD

**Issue by TadyTheFish** [Chris-Annin/AR2#14]
Not really an issue. Maybe i'm missing something so please correct me if i'm wrong.

In the excel spreadsheet and on the inverse kinematic section, cell N3 says degrees. should't it say mm or delta mm?

**Comment by Chris-Annin** [comment]
you are correct that should be mm.  ive updated a few things in the model and in a few weeks I will post another video in the kinematic series to cover changes.  thank you.
Chrhis
