### ISSUE TITLE
Screen Size on Notebook

### ISSUE THREAD

**Issue by projectholder** [Chris-Annin/AR2#16]
Hi Chris

Do you  have an idea why my screen size on my notebook does not fit proberly (see attached file)
![notebook_ar2-software_screen_size](https://user-images.githubusercontent.com/38046007/38260467-f6616eec-3767-11e8-8988-deea5b87c338.jpg)
![desktop_pc_ar2-software_screen_size](https://user-images.githubusercontent.com/38046007/38260470-f79f568e-3767-11e8-815a-d1a08d0290ce.jpg)

Best regards 

Marcel

**Comment by Chris-Annin** [comment]
yes it is the windows display zoom setting.  see screenshot in software folder called display setting.
